### PR TITLE
Create unit tests for TimePoint class

### PR DESCRIPTION
**Pull request by hutnikau**

### CODE REVIEW

**Comment by krampstudio** [comment]
Could you move the test into `test/runner/time` instead of `test/time`

**Comment by krampstudio** [comment]
The test fails to run, because of a missing value from the serialize provider : 

```
PHPUnit 5.4-g1206dd3 by Sebastian Bergmann and contributors.

EE.EE.............                                                18 / 18 (100%)

Time: 69 ms, Memory: 4.00Mb

There were 4 errors:

1) oat\taoTests\test\TimerPointTest::testSerialize with data set #0 (1459335349, 1, 2)
Missing argument 4 for oat\taoTests\test\TimerPointTest::testSerialize()

/home/bertrand/dev/projects/package-tao-act/taoTests/test/time/TimerPointTest.php:46

2) oat\taoTests\test\TimerPointTest::testSerialize with data set #1 (1459335572, 1, 2)
Missing argument 4 for oat\taoTests\test\TimerPointTest::testSerialize()

/home/bertrand/dev/projects/package-tao-act/taoTests/test/time/TimerPointTest.php:46

3) oat\taoTests\test\TimerPointTest::testUnserialize with data set #0 (1459335349, 1, 2)
Missing argument 4 for oat\taoTests\test\TimerPointTest::testUnserialize()

/home/bertrand/dev/projects/package-tao-act/taoTests/test/time/TimerPointTest.php:65

4) oat\taoTests\test\TimerPointTest::testUnserialize with data set #1 (1459335572, 1, 2)
Missing argument 4 for oat\taoTests\test\TimerPointTest::testUnserialize()

/home/bertrand/dev/projects/package-tao-act/taoTests/test/time/TimerPointTest.php:65

FAILURES!
Tests: 18, Assertions: 34, Errors: 4.
```

**Comment by hutnikau** [comment]
@krampstudio branch has been updated. Please review it again.

**Comment by jsconan** [comment]
Not all methods of TimePoint are tested, is it normal ? (getNormalizedTimestamp, getRef)

**Comment by hutnikau** [comment]
Usually there is no reason to test getters and setters but if you would like I will add tests for these methods.

**Comment by krampstudio** [comment]
The coverage gives me the TimePoint methods `getRef` and `getTag` not executed, but `getNormalizedTimestamp` is executed indirectly by the `compare` method. 
As soon as  `getRef` and `getTag` aren't simple getter but does some changes, they have to be tested.

**Comment by jsconan** [comment]
getRef and getNormalizedTimestamp do not do changes, but provides values on which we will rely.

getNormalizedTimestamp only provide an adjusted value from the timestamp, to overcome the float accuracy issues. But ok, it is not very important to test it.

However, getRef provides a consistent identifier from the tags, independently of the order (by example, ['a', b', 'c] an ['b','c','a'] will provide the same identifier). So I think it is important to be sure these values are correct.

**Comment by hutnikau** [comment]
I have added necessary tests. Coverage is 100% now.

**Pull request merged**
